remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Window Suppliers and Models with High Performance 2 Pane Options from NRCan DataBases]
description: [ Possible Window Supplier Options For Your Home:- Double Pane Casement ]

